# Supabase Configuration
# This file configures Supabase CLI behavior

[project]
# project_ref = "your-project-ref"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[edge_runtime]
# runtime = "deno"

[functions]
# runtime = "deno"


[functions.user]
verify_jwt = false


[functions.mail-recv]
verify_jwt = false

[functions.mail]
verify_jwt = false

[functions.newsletter]
verify_jwt = false


[functions.slack-notify]
verify_jwt = true